### ISSUE TITLE
AttributeError: 'DVSGestureDataset' object has no attribute 'files_train'

### ISSUE THREAD

**Issue by Helloworld-Le** [BICLab/Attention-SNN#2]
Traceback (most recent call last):
  File "/content/Attention-SNN/MA_SNN/DVSGestures/Att_SNN_CNN.py", line 45, in <module>
    main()
  File "/content/Attention-SNN/MA_SNN/DVSGestures/Att_SNN_CNN.py", line 41, in main
    Att_SNN.main()
  File "/content/Attention-SNN/MA_SNN/DVSGestures/CNN/Att_SNN.py", line 32, in main
    create_data(config=config)
  File "/content/Attention-SNN/MA_SNN/DVSGestures/DVS_Gesture_utils/dataset.py", line 8, in create_data
    config.train_dataset = create_datasets(
  File "/content/Attention-SNN/MA_SNN/DVSGestures/DVS_gesture_data_process/DVS_Gesture_dataloders.py", line 246, in create_datasets
    train_d = DVSGestureDataset(root,
  File "/content/Attention-SNN/MA_SNN/DVSGestures/DVS_gesture_data_process/DVS_Gesture_dataloders.py", line 57, in __init__
    self.n = len(self.files_train)
AttributeError: 'DVSGestureDataset' object has no attribute 'files_train'

**Comment by yangynan** [comment]
请问你解决了吗，我也是这个问题

**Comment by BICLab** [comment]
This may be because the program did not find the dataset at the given path,
i.e., os.walk(root_train) in the following code returned an empty list.

root_train = os.path.join(self.root, 'train')
for _, _, self.files_train in os.walk(root_train):
    pass

**Comment by Mouseminar** [comment]
我也遇到这个问题了，原来是我没有运行/MA_SNN/DVSGestures/data/DVS_Gesture.py这个代码，导致数据集没有划分
